### ISSUE TITLE
Documentation issue in the wip/2.0.0 branch

### ISSUE THREAD

**Issue by jayS-de** [raml-org/raml-tck#110]
The readme says the test-config.json file has a field ```ramlVersion```. Actually the test-config.json files have this field in lower case. So either the readme has to be updated or the test-config.json files have to be changed

**Comment by sichvoge** [comment]
Thanks. Changed it. Also added `deprecated` since that field probably disappears with our plans to use the TCK for our [API Modeling Framework](https://github.com/raml-org/api-modelling-framework) as well. In that, we have multi-spec support so it will not only be for RAML.
