### ISSUE TITLE
Test format for wip/2.0.0 branch

### ISSUE THREAD

**Issue by antoniogarrote** [raml-org/raml-tck#111]
In order to extend the TCK to support OpenAPI and AMF model formats, we need to introduce some way of relate files for the same test case encoding the information in the different syntaxes.

We have agreed to do this using a particular convention:

test-config.json will still have a 'input' property, but instead of pointing to a raml file it will just introduce a string that can be used to locate the related files for the test case in the following way:

- RAML file: add '.raml' extension
- OpenAPI file: add '.oas' extension
- AMF file: add '.amf' extension
- AMF resolved model file: add '.resolved.amf' extension

If the test is a negative test case, the error files with the identifiers of the failing errors can be located in the following way:

- Errors for the RAML profile: add '.raml.errors' extension
- Errors for the OpenAPI profile: add '.oas.errors' extension

**Comment by sichvoge** [comment]
LGTM 👍

**Comment by sichvoge** [comment]
Fixed! Thanks Antonio.
